local tux = require("tux")
local assert = require("luassert")

describe("tux.parse", function()
  describe("with a target", function()
    it("generates a tmux command", function()
      assert.are.same(tux.parse("ls", "{last}"), [[tmux send -t {last} 'ls' Enter]])
    end)
  end)

  describe("without a target", function()
    it("generates a tmux command", function()
      assert.are.same(tux.parse("ls"), [[tmux send 'ls' Enter]])
    end)
  end)
end)
